#!/usr/bin/env node

const { exec, spawn } = require("child_process");
const homedir = require('os').homedir();
// console.log(homedir)
const ls = spawn("ls", ["-lh", "--color=auto", `${homedir}/.config`]);

ls.stdout.on("data", (data) => {
	console.log(`stdout: ${data}`);
});

ls.stderr.on("data", (data) => {
	console.error(`stderr: ${data}`);
});

ls.on("close", (code) => {
	console.log(`child process exited with code ${code}`);
});
